import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 md:px-6 py-16 md:py-24">
      <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
      <p className="text-sm text-[#555] mb-12">Last updated: March 2026</p>

      <div className="prose-custom space-y-8 text-[#ccc] text-sm leading-relaxed">
        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using kualia.ai (&quot;the Platform&quot;), you agree to be bound by these
            Terms of Service. If you do not agree, do not use the Platform. We reserve the right to
            update these terms at any time; continued use after changes constitutes acceptance.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            kualia.ai is an AI-powered platform for generating reinforcement learning environments,
            training RL agents, conducting automated research experiments, and generating research
            papers. The Platform uses third-party AI models (including but not limited to OpenAI,
            Anthropic, and Moonshot) to provide its services.
          </p>
        </Section>

        <Section title="3. Account Registration">
          <p>
            You must create an account to use the Platform. You are responsible for maintaining the
            confidentiality of your account credentials and for all activities under your account.
            You must provide accurate information and be at least 16 years of age. We reserve the
            right to suspend or terminate accounts that violate these terms.
          </p>
        </Section>

        <Section title="4. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>Use the Platform for any unlawful purpose</li>
            <li>Attempt to gain unauthorized access to any part of the Platform</li>
            <li>Interfere with or disrupt the Platform&apos;s infrastructure</li>
            <li>Use automated tools to scrape or overload the service</li>
            <li>Generate content that is harmful, abusive, or violates third-party rights</li>
            <li>Resell or redistribute the Platform&apos;s services without permission</li>
            <li>Circumvent rate limits or usage restrictions</li>
          </ul>
        </Section>

        <Section title="5. Intellectual Property">
          <p>
            <strong className="text-white">Your Content:</strong> You retain ownership of the
            environments, trained models, and research papers you create using the Platform. You
            grant kualia.ai a non-exclusive license to store and process your content solely for
            the purpose of providing the service.
          </p>
          <p className="mt-3">
            <strong className="text-white">Platform IP:</strong> The Platform&apos;s code, design,
            AI agents, documentation, and branding are owned by kualia.ai. You may not copy,
            modify, or distribute any part of the Platform without written permission.
          </p>
        </Section>

        <Section title="6. AI-Generated Content">
          <p>
            Content generated by the Platform&apos;s AI systems (including environment code, training
            configurations, and research papers) is provided &quot;as is.&quot; While we strive for
            accuracy, AI-generated content may contain errors. You are responsible for reviewing and
            validating all generated content before use in production or academic settings. Research
            papers generated by the Platform should be reviewed and edited before submission to any
            publication venue.
          </p>
        </Section>

        <Section title="7. Service Availability">
          <p>
            We aim to provide reliable service but do not guarantee uninterrupted availability. The
            Platform may be temporarily unavailable due to maintenance, updates, or circumstances
            beyond our control. We reserve the right to modify, suspend, or discontinue any feature
            at any time.
          </p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>
            To the maximum extent permitted by law, kualia.ai shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages arising from your use of the
            Platform. Our total liability shall not exceed the amount you have paid to us in the
            twelve months preceding the claim. The Platform is provided &quot;as is&quot; without
            warranties of any kind.
          </p>
        </Section>

        <Section title="9. Termination">
          <p>
            Either party may terminate this agreement at any time. Upon termination, your right to
            use the Platform ceases immediately. We may retain your data for a reasonable period to
            comply with legal obligations. You may request deletion of your data by contacting us.
          </p>
        </Section>

        <Section title="10. Governing Law">
          <p>
            These terms are governed by applicable law. Any disputes shall be resolved through
            binding arbitration or in the courts of competent jurisdiction.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            For questions about these Terms, contact us at{" "}
            <a href="mailto:legal@kualia.ai" className="text-white hover:underline">
              legal@kualia.ai
            </a>.
          </p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-base font-semibold text-white mb-3">{title}</h2>
      {children}
    </section>
  );
}
